test-cpu:
  instance_type_list:
    - t2.micro
  job_size: small
  job_type: ec2-sysbench-cpu
ec2-sysbench-cpu-small:
  instance_type_list:
    - t2.micro
    - c5.large
  job_size: small
  job_type: ec2-sysbench-cpu
ec2-sysbench-cpu-large:
  instance_type_list:
    - t2.micro
    - t2.medium
    - t2.large
    - t2.xlarge
    - t2.2xlarge
    - t3.micro
    - t3.medium
    - t3.large
    - t3.2xlarge
    - c3.large
    - c3.2xlarge
    - c3.8xlarge
    - c4.large
    - c4.2xlarge
    - c4.8xlarge
    - c5.large
    - c5.2xlarge
    - c5.18xlarge
    - m3.2xlarge
    - m4.large
    - m4.2xlarge
    - m4.16xlarge
    - m5.large
    - m5.2xlarge
    - m5.24xlarge
    - m5a.large
    - m5a.2xlarge
    - m5a.24xlarge
    - r4.large
    - r4.2xlarge
    - r4.16xlarge
    - r5.large
    - r5.2xlarge
    - r5.24xlarge
    - r5a.large
    - r5a.2xlarge
    - r5a.24xlarge
    - d2.8xlarge
  job_size: flex
  job_type: ec2-sysbench-cpu
ec2-sysbench-memory-large:
  instance_type_list:
    - t2.micro
    - t2.medium
    - t2.large
    - t2.xlarge
    - t2.2xlarge
    - t3.micro
    - t3.medium
    - t3.large
    - t3.2xlarge
    - c3.large
    - c3.2xlarge
    - c3.8xlarge
    - c4.large
    - c4.2xlarge
    - c4.8xlarge
    - c5.large
    - c5.2xlarge
    - c5.18xlarge
    - m3.2xlarge
    - m4.large
    - m4.2xlarge
    - m4.16xlarge
    - m5.large
    - m5.2xlarge
    - m5.24xlarge
    - m5a.large
    - m5a.2xlarge
    - m5a.24xlarge
    - r4.large
    - r4.2xlarge
    - r4.16xlarge
    - r5.large
    - r5.2xlarge
    - r5.24xlarge
    - r5a.large
    - r5a.2xlarge
    - r5a.24xlarge
    - d2.8xlarge
  job_size: flex
  job_type: ec2-sysbench-memory
ec2-arm-unixbench-large:
  instance_type_list:
    - a1.medium
    - a1.large
    - a1.xlarge
    - a1.2xlarge
    - a1.4xlarge
  job_size: flex
  ami_type: arm
  job_type: ec2-unixbench
ec2-unixbench-small:
  instance_type_list:
    - t2.micro
    - c5.large
  job_size: small
  job_type: ec2-unixbench
ec2-unixbench-large:
  instance_type_list:
    - t2.micro
    - t2.medium
    - t2.large
    - t2.xlarge
    - t2.2xlarge
    - t3.micro
    - t3.medium
    - t3.large
    - t3.2xlarge
    - c3.large
    - c3.2xlarge
    - c3.8xlarge
    - c4.large
    - c4.2xlarge
    - c4.8xlarge
    - c5.large
    - c5.2xlarge
    - c5.18xlarge
    - m3.2xlarge
    - m4.large
    - m4.2xlarge
    - m4.16xlarge
    - m5.large
    - m5.2xlarge
    - m5.24xlarge
    - m5a.large
    - m5a.2xlarge
    - m5a.24xlarge
    - r4.large
    - r4.2xlarge
    - r4.16xlarge
    - r5.large
    - r5.2xlarge
    - r5.24xlarge
    - r5a.large
    - r5a.2xlarge
    - r5a.24xlarge
    - d2.8xlarge
  job_size: flex
  job_type: ec2-unixbench
ec2-unixbench-append:
  instance_type_list:
    - c3.xlarge
    - c3.4xlarge
    - c4.xlarge
    - c4.4xlarge
    - c5.xlarge
    - c5.4xlarge
    - c5.9xlarge
    - m3.large
    - m3.xlarge
    - m4.xlarge
    - m4.4xlarge
    - m4.10xlarge
    - m5.xlarge
    - m5.4xlarge
    - m5.12xlarge
    - m5a.xlarge
    - m5a.4xlarge
    - m5a.12xlarge
    - r4.xlarge
    - r4.4xlarge
    - r4.8xlarge
    - r5.xlarge
    - r5.4xlarge
    - r5.12xlarge
    - r5a.xlarge
    - r5a.4xlarge
    - r5a.12xlarge
    - d2.2xlarge
    - d2.4xlarge
    - i3.16xlarge
    - h1.16xlarge
  job_size: flex
  job_type: ec2-unixbench
ec2-unixbench-m6g-small:
  instance_type_list:
    - m6g.medium
  job_size: flex
  ami_type: arm
  job_type: ec2-unixbench
ec2-unixbench-m6g:
  instance_type_list:
    - m6g.medium
    - m6g.large
    - m6g.xlarge
    - m6g.2xlarge
    - m6g.4xlarge
    - m6g.8xlarge
    - m6g.12xlarge
    - m6g.16xlarge
  job_size: flex
  ami_type: arm
  job_type: ec2-unixbench
